variable "aws_region" {
  description = "AWS region for resources and SSM."
  type        = string
  default     = "us-east-1"
}

variable "project_name" {
  description = "Project name used in tags and SSM path."
  type        = string
}

variable "environment" {
  description = "Environment name (e.g. dev)."
  type        = string
  default     = "dev"
}

variable "extra_tags" {
  description = "Additional tags merged into defaults."
  type        = map(string)
  default     = {}
}

# --- Supabase (set in terraform.tfvars; never commit real tfvars) ---

variable "supabase_url" {
  description = "Supabase project URL."
  type        = string
}

variable "supabase_anon_key" {
  description = "Supabase anon (public) key."
  type        = string
  sensitive   = true
}

variable "supabase_service_role_key" {
  description = "Supabase service_role key (server-only)."
  type        = string
  sensitive   = true
}

variable "supabase_jwt_secret" {
  description = "Optional Supabase JWT secret from project API settings."
  type        = string
  sensitive   = true
  default     = null
}

variable "manage_supabase_credentials_in_ssm" {
  description = "When true, write Supabase values from tfvars into SSM Parameter Store."
  type        = bool
  default     = true
}

variable "api_lambda_bundle_path" {
  description = "Path to the built Lambda entry file (generated by `npm run build:lambda -w @lattice/api`)."
  type        = string
  default     = "../../../../apps/api/dist-lambda/index.js"
}

variable "api_lambda_runtime" {
  description = "Lambda runtime for the API function."
  type        = string
  default     = "nodejs20.x"
}

variable "api_lambda_timeout_seconds" {
  description = "API Lambda timeout in seconds."
  type        = number
  default     = 15
}

variable "api_lambda_memory_mb" {
  description = "API Lambda memory size in MB."
  type        = number
  default     = 512
}

variable "api_lambda_reserved_concurrency" {
  description = "Optional reservation limit for concurrent API Lambda executions. AWS enforces a minimum unreserved concurrency per region; setting this consumes from that pool and apply can fail if unreserved would drop below that minimum. Omit or null to leave the function on the unreserved pool (no explicit reservation)."
  type        = number
  nullable    = true
  default     = null
}

variable "api_gateway_throttling_rate_limit" {
  description = "Steady-state request rate limit for API Gateway default stage."
  type        = number
  default     = 10
}

variable "api_gateway_throttling_burst_limit" {
  description = "Burst request limit for API Gateway default stage."
  type        = number
  default     = 20
}

variable "api_cors_extra_origins" {
  description = "Optional comma-separated extra browser origins for the Express CORS middleware (e.g. https://app.example.com). The deployed CloudFront HTTPS origin and local dev (3001) origins are always included."
  type        = string
  default     = ""
}

variable "things_table_name" {
  description = "Supabase table name used by the API repository."
  type        = string
  default     = "things"
}

variable "enable_budget_alerts" {
  description = "When true, create AWS Budget alerts for monthly spend."
  type        = bool
  default     = true
}

variable "monthly_cost_budget_limit_usd" {
  description = "Monthly cost budget ceiling in USD for this environment."
  type        = number
  default     = 10
}

variable "budget_alert_email_addresses" {
  description = "Email recipients for budget alerts (requires subscription confirmation in AWS)."
  type        = list(string)
  default     = []
}

variable "enable_api_schedule_controls" {
  description = "When true, create scheduled API pause/resume controls via EventBridge Scheduler."
  type        = bool
  default     = false
}

variable "api_pause_schedule_expression" {
  description = "Scheduler cron/rate expression for API pause (set reserved concurrency to 0)."
  type        = string
  default     = "cron(0 2 * * ? *)"
}

variable "api_resume_schedule_expression" {
  description = "Scheduler cron/rate expression for API resume (remove reserved concurrency cap override)."
  type        = string
  default     = "cron(0 13 * * ? *)"
}

variable "api_schedule_timezone" {
  description = "Timezone used by EventBridge Scheduler expressions."
  type        = string
  default     = "UTC"
}
